# Generated by Django 5.2.3 on 2025-06-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Name or Company Name"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("juridica", "Cédula Jurídica"),
                            ("fisica", "Cédula Física"),
                            ("dimex", "DIMEX"),
                            ("otro", "Otro (Especificar en notas)"),
                        ],
                        default="fisica",
                        max_length=10,
                        verbose_name="ID Type",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if not applicable or using 'Otro' ID type",
                        max_length=50,
                        null=True,
                        verbose_name="ID Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Physical Address"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Primary Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Primary Phone",
                    ),
                ),
                (
                    "secondary_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Secondary Email",
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Secondary Phone",
                    ),
                ),
                (
                    "notes_cxc",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Notes (Accounts Receivable)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Name or Company Name"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("juridica", "Cédula Jurídica"),
                            ("fisica", "Cédula Física"),
                            ("dimex", "DIMEX"),
                            ("otro", "Otro (Especificar en notas)"),
                        ],
                        default="juridica",
                        max_length=10,
                        verbose_name="ID Type",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if not applicable or using 'Otro' ID type",
                        max_length=50,
                        null=True,
                        verbose_name="ID Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Physical Address"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Primary Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Primary Phone",
                    ),
                ),
                (
                    "secondary_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Secondary Email",
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Secondary Phone",
                    ),
                ),
                (
                    "notes_cxp",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes (Accounts Payable)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
        ),
    ]
