# Generated by Django 5.2.3 on 2025-06-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0002_customer_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="supplier_name",
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoicing.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoicing.supplier",
                verbose_name="Supplier",
            ),
        ),
    ]
